### ISSUE TITLE
XML format error v0.9.16 and v0.9.17

### ISSUE THREAD

**Issue by nextgenusfs** [bbuchfink/diamond#191]
Thanks for development and continued maintenance of `diamond`!  I've run into an XML output bug in diamond versions newer than v0.9.14 (I've only tested v0.9.16 and v0.9.17).  Here's is what I'm seeing:

Using a blastp search and xml output like this:
```
diamond blastp --sensitive --query evm.round1.proteins.fa --threads 6 \
    --out repeats_v0.9.17.xml --db /usr/local/share/funannotate/repeats.dmnd \
    --evalue 1e-10 --max-target-seqs 1 --outfmt 5
```
I'm then parsing these data using the Biopython Blast-XML parser. 
```
with open(blast_tmp, 'rU') as results:
    for qresult in SearchIO.parse(results, "blast-xml"):
        hits = qresult.hits
        qlen = qresult.seq_len
        ID = qresult.id
        num_hits = len(hits)
        if num_hits > 0:
            length = 0
            for i in range(0,len(hits[0].hsps)):
                length += hits[0].hsps[i].aln_span
            pident = hits[0].hsps[0].ident_num / float(length)
            sys.stdout.write("%s\t%s\t%f\t%s\n" % (ID, hits[0].id, pident, hits[0].hsps[0].evalue))
```
With v0.9.16 and v0.9.17, biopython is throwing the following error:
```
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/Users/jon/miniconda2/lib/python2.7/site-packages/Bio/SearchIO/__init__.py", line 314, in parse
    for qresult in generator:
  File "/Users/jon/miniconda2/lib/python2.7/site-packages/Bio/SearchIO/BlastIO/blast_xml.py", line 214, in __iter__
    for qresult in self._parse_qresult():
  File "/Users/jon/miniconda2/lib/python2.7/site-packages/Bio/SearchIO/BlastIO/blast_xml.py", line 265, in _parse_qresult
    for event, qresult_elem in self.xml_iter:
  File "<string>", line 91, in next
cElementTree.ParseError: mismatched tag: line 11579, column 4
```
When I trace the offending line in the XML file, it corresponds to a closing tag `  </Hit_hsps>` that seems to be in the wrong place, i.e.
```
<Iteration_hits>
  </Hit_hsps>
</Hit>
<Hit>
  <Hit_num>2</Hit_num>
  <Hit_id>Ginger2-1_BF_DNA-Ginger</Hit_id>
  <Hit_def>819-3794 via genewise with Ginger2-1_MG, 2 introns (1118:2125, 2785:3087) (second intron is open and in-frame; it could alternatively be at 3078:3390 or be absent) [Branchiostoma floridae]</Hit_def>
  <Hit_accession>Ginger2-1_BF_DNA-Ginger</Hit_accession>
  <Hit_len>555</Hit_len>
  <Hit_hsps>
    <Hsp>
      <Hsp_num>1</Hsp_num>
      <Hsp_bit-score>102.1</Hsp_bit-score>
      <Hsp_score>253</Hsp_score>
      <Hsp_evalue>7.2e-22</Hsp_evalue>
      <Hsp_query-from>135</Hsp_query-from>
      <Hsp_query-to>251</Hsp_query-to>
      <Hsp_hit-from>195</Hsp_hit-from>
      <Hsp_hit-to>312</Hsp_hit-to>
      <Hsp_query-frame>0</Hsp_query-frame>
      <Hsp_hit-frame>0</Hsp_hit-frame>
      <Hsp_identity>51</Hsp_identity>
      <Hsp_positive>73</Hsp_positive>
      <Hsp_gaps>2</Hsp_gaps>
      <Hsp_align-len>118</Hsp_align-len>
         <Hsp_qseq>YPLKSKHAEPIAERFAQFITAFLPPKIMQSDNGKEF-KGALLILLRKY-GIQVVNGAPRSPQTQGLVEQANGVVENKLRAWKMDHGSTEWKDGLLEVTLAMNTQIHSTIGCAPAELLF</Hsp_qseq>
         <Hsp_hseq>HPLTSKRASGVAEKLVQTFCLFGSPHILQSDNGKEFVAGVINELTEKWPGLVIIHGRPRHPQSQGCIERANGDLQLKLGKWMEEHPEKGWVEGLQHVTYAMNTSVCATTGKSPYAVVF</Hsp_hseq>
      <Hsp_midline>+PL SK A  +AE+  Q    F  P I+QSDNGKEF  G +  L  K+ G+ +++G PR PQ+QG +E+ANG ++ KL  W  +H    W +GL  VT AMNT + +T G +P  ++F</Hsp_midline>
    </Hsp>
  </Hit_hsps>
</Hit>
</Iteration_hits>
```
This same search with v0.9.14 looks like this:
```
<Iteration_hits>
<Hit>
  <Hit_num>1</Hit_num>
  <Hit_id>Ginger2-1_BF_DNA-Ginger</Hit_id>
  <Hit_def>819-3794 via genewise with Ginger2-1_MG, 2 introns (1118:2125, 2785:3087) (second intron is open and in-frame; it could alternatively be at 3078:3390 or be absent) [Branchiostoma floridae]</Hit_def>
  <Hit_accession>Ginger2-1_BF_DNA-Ginger</Hit_accession>
  <Hit_len>555</Hit_len>
  <Hit_hsps>
    <Hsp>
      <Hsp_num>1</Hsp_num>
      <Hsp_bit-score>102.1</Hsp_bit-score>
      <Hsp_score>253</Hsp_score>
      <Hsp_evalue>7.2e-22</Hsp_evalue>
      <Hsp_query-from>135</Hsp_query-from>
      <Hsp_query-to>251</Hsp_query-to>
      <Hsp_hit-from>195</Hsp_hit-from>
      <Hsp_hit-to>312</Hsp_hit-to>
      <Hsp_query-frame>0</Hsp_query-frame>
      <Hsp_hit-frame>0</Hsp_hit-frame>
      <Hsp_identity>51</Hsp_identity>
      <Hsp_positive>73</Hsp_positive>
      <Hsp_gaps>2</Hsp_gaps>
      <Hsp_align-len>118</Hsp_align-len>
         <Hsp_qseq>YPLKSKHAEPIAERFAQFITAFLPPKIMQSDNGKEF-KGALLILLRKY-GIQVVNGAPRSPQTQGLVEQANGVVENKLRAWKMDHGSTEWKDGLLEVTLAMNTQIHSTIGCAPAELLF</Hsp_qseq>
         <Hsp_hseq>HPLTSKRASGVAEKLVQTFCLFGSPHILQSDNGKEFVAGVINELTEKWPGLVIIHGRPRHPQSQGCIERANGDLQLKLGKWMEEHPEKGWVEGLQHVTYAMNTSVCATTGKSPYAVVF</Hsp_hseq>
      <Hsp_midline>+PL SK A  +AE+  Q    F  P I+QSDNGKEF  G +  L  K+ G+ +++G PR PQ+QG +E+ANG ++ KL  W  +H    W +GL  VT AMNT + +T G +P  ++F</Hsp_midline>
    </Hsp>
  </Hit_hsps>
</Hit>
</Iteration_hits>
```

**Comment by bbuchfink** [comment]
Sorry for that, I have just commited a patch that should fix this and will
post a new release later.
