### ISSUE TITLE
diamond stuck at all-vesus-all blastp Done 80 of 100

### ISSUE THREAD

**Issue by tengchong** [bbuchfink/diamond#228]
Hi all, 

My diamond stuck in OrthoFinder, so I interrupted it at all-vesus-all Done 80 of 100. I tried to run it again now. But here's what I got:
OrthoFinder version 2.2.7 Copyright (C) 2014 David Emms

2018-09-11 10:10:23 : Starting OrthoFinder
16 thread(s) for highly parallel tasks (BLAST searches etc.)
1 thread(s) for OrthoFinder algorithm

Checking required programs are installed
----------------------------------------
Test can run "mcl -h" - ok
Test can run "fastme -i /newdata/data2/homes/teng/SOL/OrthoFinder/prot_1/SimpleTest.phy -o /newdata/data2/homes/teng/SOL/OrthoFinder/prot_1/SimpleTest.tre" - ok

Dividing up work for BLAST for parallel processing
--------------------------------------------------
2018-09-11 10:10:29 : Creating diamond database 1 of 10
2018-09-11 10:10:29 : Creating diamond database 2 of 10
2018-09-11 10:10:30 : Creating diamond database 3 of 10
2018-09-11 10:10:30 : Creating diamond database 4 of 10
2018-09-11 10:10:30 : Creating diamond database 5 of 10
2018-09-11 10:10:31 : Creating diamond database 6 of 10
2018-09-11 10:10:31 : Creating diamond database 7 of 10
2018-09-11 10:10:31 : Creating diamond database 8 of 10
2018-09-11 10:10:31 : Creating diamond database 9 of 10
2018-09-11 10:10:32 : Creating diamond database 10 of 10

Running diamond all-versus-all
------------------------------
Using 16 thread(s)
2018-09-11 10:10:32 : This may take some time....
2018-09-11 10:10:32 : Done 0 of 100
2018-09-11 10:19:54 : Done 10 of 100
2018-09-11 10:24:33 : Done 20 of 100
2018-09-11 10:29:55 : Done 30 of 100
2018-09-11 10:33:47 : Done 40 of 100
2018-09-11 10:37:51 : Done 50 of 100
2018-09-11 10:41:35 : Done 60 of 100
2018-09-11 10:45:41 : Done 70 of 100
2018-09-11 10:48:21 : Done 80 of 100
^CTraceback (most recent call last):
  File "orthofinder/orthofinder.py", line 1586, in <module>
  File "orthofinder/orthofinder.py", line 1389, in RunSearch
  File "multiprocessing/process.py", line 145, in join
  File "multiprocessing/forking.py", line 148, in wait
  File "multiprocessing/forking.py", line 133, in poll
Process Process-1:
KeyboardInterrupt
Traceback (most recent call last):
Failed to execute script orthofinder
  File "multiprocessing/process.py", line 258, in _bootstrap
Process Process-2:
Traceback (most recent call last):
  File "multiprocessing/process.py", line 114, in run
  File "orthofinder/scripts/parallel_task_manager.py", line 72, in _I_Spawn_Processes
  File "multiprocessing/process.py", line 258, in _bootstrap
KeyboardInterrupt
  File "multiprocessing/process.py", line 114, in run
  File "orthofinder/scripts/util.py", line 119, in Worker_RunCommand
  File "orthofinder/scripts/util.py", line 79, in RunCommand
  File "subprocess.py", line 493, in call
  File "subprocess.py", line 1301, in wait
  File "subprocess.py", line 478, in _eintr_retry_call
KeyboardInterrupt

Any suggesion? Please let me know!

thanks,
TC

**Comment by tengchong** [comment]
Thank you, Benjamin!

Good news! The job is done! It took 7 hours to update the progress from "Done 80 out of 100" to "Done all-versus-all". But it's done! So problem solved!
