### ISSUE TITLE
Diamond -> MEGAN with long reads

### ISSUE THREAD

**Issue by devindrown** [bbuchfink/diamond#356]
Hoping I can find some help over here. I'm trying to replicate the long-read pipeline in [Arumugam et al (2019)](https://doi.org/10.1186/s40168-019-0665-y) with some MinION data

using `diamond v0.9.33.134` and `MEGAN_Community_unix_6_18_11`

Step 1) Generate a .daa file with long-reed parameters
```
diamond blastx --long-reads -d /mnt/storage/diamondDB/nr.dmnd -q sample.fasta --outfmt 100 --out sample.fasta.longreads.daa -c1 -b10 --tmpdir /dev/shm
```
Step 2) Use megan tool `daa-meganizer` to prepare the .daa file
```
$HOME/megan/tools/daa-meganizer -i sample.fasta.longreads.daa --mapDB /mnt/storage/diamondDB/megan-map-Oct2019.db --longReads --lcaAlgorithm longReads --lcaCoveragePercent 51 --readAssignmentMode alignedBases -t 16
```
This command results in an error and halts.
```
Binning reads...
Binning reads Analyzing alignments
Caught:
java.lang.ArrayIndexOutOfBoundsException: Index 27 out of bounds for length 27
        at megan/megan.daa.io.DAAMatchRecord.parseTranscript(DAAMatchRecord.java:131)
        at megan/megan.daa.io.DAAMatchRecord.parseBuffer(DAAMatchRecord.java:93)
        at megan/megan.daa.io.DAAParser.readQueryAndMatches(DAAParser.java:294)
        at megan/megan.daa.connector.ReadBlockGetterDAA.getReadBlock(ReadBlockGetterDAA.java:125)
        at megan/megan.data.AllReadsIterator.next(AllReadsIterator.java:75)
        at megan/megan.data.AllReadsIterator.next(AllReadsIterator.java:30)
        at megan/megan.algorithms.DataProcessor.apply(DataProcessor.java:213)
        at megan/megan.core.Document.processReadHits(Document.java:536)
        at megan/megan.daa.Meganize.apply(Meganize.java:106)
        at megan/megan.tools.DAAMeganizer.run(DAAMeganizer.java:250)
        at megan/megan.tools.DAAMeganizer.main(DAAMeganizer.java:63)
```

I realize the error is occurring when using Megan and not diamond, but was curious about the output form diamond.

I tried the same input FASTA file without the `--long-reads` option. The below commands didn't generate an error.
```
diamond blastx -d /mnt/storage/diamondDB/nr.dmnd -q sample.fasta --outfmt 100 --out sample.fasta.daa -c1 -b10 --tmpdir /dev/shm
$HOME/megan/tools/daa-meganizer -i sample.fasta.daa --mapDB /mnt/storage/diamondDB/megan-map-Oct2019.db --longReads --lcaAlgorithm longReads --lcaCoveragePercent 51 --readAssignmentMode alignedBases -t 16
```

If anyone has ideas I would be grateful for suggestions.
-Devin

**Comment by bbuchfink** [comment]
Please try to run `diamond view` on the same DAA file and see if that works, otherwise the DAA file is corrupted.

**Comment by devindrown** [comment]
It looks like the DAA file is corrupted. Any thoughts on what is causing the corruption? I've tried this on two different machines and a couple of different small nanopore datasets.

```
diamond view -a sample.fasta.longreads.daa -o output.longreads.view --outfmt 6

diamond v0.9.33.134 (C) Max Planck Society for the Advancement of Science
Documentation, support and updates available at http://www.diamondsearch.org

#CPU threads: 48
Loading subject IDs... Killed
```

**Comment by bbuchfink** [comment]
Can you type `dmesg` after running view and show me the output? How much memory does your system have?

**Comment by devindrown** [comment]
128 G for memory

last line of output from `dmesg` is

```
[6444182.349167] Out of memory: Kill process 20053 (diamond) score 987 or sacrifice child
[6444182.349173] Killed process 20053 (diamond) total-vm:145869524kB, anon-rss:130119356kB, file-rss:4kB
```

When I ran the view command on the .daa file generated without the -F 15 option, 
```
diamond view -a sample.fasta.daa -o output.view --outfmt 6
```
The output it is extremely large and has lots of IDs concatenated together (see below) 

```
6ac9577b-ad2b-4170-88a1-2df5fae3fc9b    OFW44224.1KYF81506.1WP_020736541.1WP_061612059.1SFS39420.1WP_071136339.1WP_071137180.1HBC28
199.1WP_090991508.1WP_057951668.1WP_025065171.1WP_139224234.1WP_009036504.1OQB30183.1WP_143102543.1WP_122970223.1WP_139224125.1WP_1
11613291.1WP_139162656.1WP_143102474.1SNS69845.1NDP20628.1HDH10613.1HAG10459.1AMS26305.1WP_166774084.1WP_166774026.1AMS25916.1MAZ36
```

Another user on the [MEGAN forums](http://megan.informatik.uni-tuebingen.de/t/meganizer-daa-file-arrayindexoutofboundsexception-error/1508/5) noted the same issue.

**Comment by bbuchfink** [comment]
This should fix the issue with view: a0a9cd37b5b44e47e021fbcf7ab114db71eff677

It does not really explain the Megan error though, since this bug did not lead to a corruption of DAA files, only to an error in `diamond view`.

**Comment by devindrown** [comment]
Thanks for the quick fix. The .daa files now processes without error in `diamond view`. However, the downstream error with Megan still occurs. I'll continue to follow up with the Megan community.

**Comment by husonlab** [comment]
Hi Benjamin, what did you have to fix in diamond view? I would think that it is likely that there is a similar bug in MEGAN's version of "view"

**Comment by bbuchfink** [comment]
The method for reading the subject titles from the DAA file didn't clear the string buffer after each read. Pretty unlikely that Megan has the exact same bug.

**Comment by husonlab** [comment]
I just took a look at the problem in MEGAN:

When parsing a packed transcript (describing a match), for a substitution edit operation, the program gets a 27 as letter position in alphabet.
However, the alphabet that MEGAN uses is represented by this array: "ARNDCQEGHILKMFPSTWYVBJZX*/\\”
which is exactly 27 letters long. So my question is whether DIAMOND now uses 28 or more letters, and what would those be?

Thanks
daniel

**Comment by bbuchfink** [comment]
Turns out I did change the alphabet size without realizing the effect on the DAA format at the time. The change is in place since version 0.9.31 and can be detected by a build version of >=132 in the header. The codes for the 2 frameshift operations are both increased by 1.

**Comment by devindrown** [comment]
Thank you both for helping troubleshoot and ultimately provide quick fixes for this issue. I appreciate the help.
-Devin

**Comment by lucyintheskyzzz** [comment]
Hi! I am unable to get Megan to meganize my .daa file.  It keeps saying: "input file not daa file"

(/lustre/project/taw/share/conda-envs/diamond-env) [kvigil@cypress1 diamond]$ diamond view -a ONR100623barcode04.daa
 -o output.view
diamond v2.1.8.162 (C) Max Planck Society for the Advancement of Science, Benjamin Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 40
Loading subject IDs... Error: Input file is not a DAA file.

**Comment by lucyintheskyzzz** [comment]
Hi I ended up doing the correct -f 100 code to create the daa file, then I meganized them in Megan using command line and it works now:

daa-meganizer -i ONR10623barcode04.daa -mdb /lustre/project/taw/share/conda-envs/megan/megan-map-Feb2022.db
